spring.application.name=customer-management

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/customer_management_db
spring.datasource.username=root
spring.datasource.password=Ankit@2345

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8081
